### ISSUE TITLE
Chunks being loaded before world being loaded

### ISSUE THREAD

**Issue by citylion** [CivMC/Civ#11]
*Low priority

Been getting this error hundreds of times on startup forever. 

I think it relates to multiverse. Can we get something added to ensure a world is loaded before its chunks are called?

[snippetlog.txt](https://github.com/CivMC/CivModCore/files/10780461/snippetlog.txt)

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
