### ISSUE TITLE
CitadelDAO - Code Style issues, SQL Statement Parameter binding

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#113]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L367

* Issue:
Some statements have explicit parameter binding, some don't. This should be unified to binding functions across all methods.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
