### ISSUE TITLE
CitadelDAO - Potential Deadlock

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#114]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L390

* Issue:
Code acquires a connection, then calls the insert consumer which may also acquire connections without passing the existing connection. This may lead to resource exhaustion and the inserter being unable to acquire the necessary connection to continue. This will deadlock the thread.

* Solution:
Pass the connection which already exists in read-write mode.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
