### ISSUE TITLE
CitadelDAO - Connection names are misleading, Connection type can be readonly in many cases.

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#115]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L32

* Issue:
- Connection name is "insertConnection" but no inserts are performed.
- Connection can be readonly.

* Solution:
Rename connections and apply readonly mode.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
