### ISSUE TITLE
CitadelDAO - Persistence Semantics are wonky

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#122]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L50

* Issue:
The current solution tries to delete reinforcements and then insert reinforcements. This may cause a collision in the database (same key for block location), because the deletion part can fail silently in the current implementation.

* Solution:
Use transactions and proper error state management.

* Linked issues:
https://github.com/CivMC/Civ/issues/125

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
