### ISSUE TITLE
CitadelDAO - Logging

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#123]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L32

* Issue:
Logging calls can be expensive and should be collapsed into a single call instead of repeatedly calling Logger.info(). Also string concatenation is run before calling the logger and might introduce unnecessary call overhead.

* Solution:
Use the logging format solutions provided by the logging framework.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
