### ISSUE TITLE
CitadelDAO - Timings

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#124]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L32

* Issue:
Logger takes timings via `System.currentTimeMillis();`. This is discouraged in the standard (`System.currentTimeMillis();` may be a blocking call.)

* Solution:
Use proper metrics. https://metrics.dropwizard.io/4.2.0/

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
