### ISSUE TITLE
Citadel DAO - Dangerous connection & commit management

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#125]
* Code Location:
https://github.com/CivMC/Citadel/blob/23a41a90335ad6d96fd2712df8cea26a1c0ed5a1/paper/src/main/java/vg/civcraft/mc/citadel/model/CitadelDAO.java#L50

* Issue:
Multiconnection request, fumbling autocommit and overall behaviour in this method is dangerous, and wrong. This code can deadlock on connection exhaustion. If the thread releases the connection and then tries to reacquire it, the semantically meant transaction will be left dangling in an unfinished state.

* Solution:
Use transactions and one connection.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
