### ISSUE TITLE
Add Repairables tag

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#13]
ItemExchange has a [config-section](https://github.com/CivMC/ItemExchange/blob/e064ccae7bfb2827ca8ebe2447505c41f406ad2b/paper/src/main/resources/config.yml#L27-L79) that enumerates all repairable items. However, both the default config and [CivDocker config](https://github.com/CivMC/CivDocker/issues/68) lack Nether items.

iirc I wrote this config-section as a quick solution as [almost] *every* item-meta inherits both `Damageable` and `Repairable`, so you cannot do a quick and dirty `instanceof` test to determine whether an item can be damaged or repaired. I was able to come up with a solution a fair while ago for the `Damageable` problem ([see here](https://github.com/CivMC/CivModCore/blob/321ab959cfa72546551eb2600db6fa56e6bc742f/paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemUtils.java#L390-L410)) by conditioning the return on the item material's maximum durability. `Repairable` however has remained ellusive. 

I suggest therefore that REPAIRABLE be added to [MoreTags](https://github.com/CivMC/CivModCore/blob/321ab959cfa72546551eb2600db6fa56e6bc742f/paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/MoreTags.java) and coming up with some reliable test so that there's no longer a need to manually test and update the config.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
