### ISSUE TITLE
Print bastion info on-hit

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#134]
This issue is equally relevant to JukeAlert: punching a bastion in `/cti` mode should display information about the bastion like whether it's broken, what type it is, etc. For JukeAlert on CivMC, it's pretty easy to tell since our configurations use vanilla noteblocks and jukeboxes, but Bastion uses custom items. You can make an educated guess that a sponge surrounded by obby is a vault bastion when coupled the scoreboard info, but it's uncertain, particularly when there's overlapping fields. With that in mind, you could surround an ordinary sponge or quartz block in obby and you genuinely would not be able to tell.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
