### ISSUE TITLE
Breaking bastions is a little resource intensive

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#135]
Probably room for improvement regarding resource usage of Bastion plugin when players are breaking bastions. At times it can be resource heavy and cause lag issues, especially if multiple bastions are being broken by multiple players. 

https://timings.aikar.co/dev/?id=48ab57eaccbd48268a5648436dcbc30d
https://spark.lucko.me/NE8Xx049Wo

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
