### ISSUE TITLE
Re-enable /bsl

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/Civ#136]
# Background

The `/bsl` command used to show a list of all bastions the player had access to. This was invaluable for managing one's bastions. The usefulness was comparable to that of `/jalist`, which lists all snitches the player has access to.

However, `/bsl` was later disabled as it allowed for nearly real-time monitoring of bastions and therefore could serve as an early warning system against all attacks, if automated.

# Current pain points

 - No easy way to share bastion locations across nation members. It's technically possible to have everyone in a nation run a script that would share placed bastion locations with everyone else, but that's prohibitively complex to be a realistic solution.
 - No realistic way of finding misaligned bastions
 - No realistic way of ever finding broken, and especially damaged, bastions

# Proposal

**Bastion damage events and breaks by players not on their groups should not be reflected in `/bsl`  until some time has passed (two weeks?).**

This would eliminate the problematic early warning function of `/bsl` entirely while not hindering its usefulness for legitimate uses.

# Rejected proposals

## Simply add a cooldown to `/bsl`
 - The last `/bsl` implementation only exposed the bastions via text, with pagination. This required multiple invocations of `/bsl` before a full list of bastions could be shown. Therefore a simple cooldown would not work.
 - Even if `/bsl` was modified to use a GUI, like the current `/jalist` implementation does, a cooldown would mean that if a player accidentally closed their window at any time, they'd have to wait for the cooldown to reset.
 - Gives a big advantage to botters over regular players. It'd be technically possible to still implement an early warning system by cycling accounts that run a `/bsl` scraping script.

## Delay all bastion state shown in `/bsl` by some time

This would hinder certain legitimate usages of the command:
 - Spotting bastion grid mistakes in real time, as they're being placed
 - Spotting insiding in real time (friendly player breaks a friendly bastion maliciously)

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
