### ISSUE TITLE
Add option to disallow placement on overlap

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#139]
Right now the only option on bastion overlap is to add a damage modifier, it would be nice to also have the option to disallow placement of bastions with certain overlaps. Especially in tandem with CivMC/Civ#140 to allow more granularity in allowing overlap for some bastion types with additional damage, and entirely preventing overlap with other bastion types.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
