### ISSUE TITLE
iirc, we've historically been hesitant to expand the `.editorconfig` as you have with a46096288e482a8313227dd9bd035d758a3128c5 because not all contributors use IntelliJ

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#14]
> iirc, we've historically been hesitant to expand the `.editorconfig` as you have with a46096288e482a8313227dd9bd035d758a3128c5 because not all contributors use IntelliJ

_Originally posted by @Protonull in https://github.com/CivMC/CivModCore/issues/74#issuecomment-1160660221_

The keys will count for intellij only if eclipse & co do not support them. But in either case, you can't expect people who work professionally with java to adapt the civmc code style for all their work, because civmc is to timid to adapt some changes to the editorconfig, that only impact, in the worst case, intellij users. I think editing the editorconfig and leaving eclipse & co useres where they were is perfectly acceptable in this case.

> I cannot comment on the comment on the commit. So this goes here now.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
