### ISSUE TITLE
Any owner can steal the group making primary ownership almost useless

### ISSUE THREAD

**Issue by drekamor** [CivMC/Civ#145]
If this permission can be toggled for OWNER, primary owner is almost useless because any other owner can steal the group by enabling this perm for admins, demoting themselves to admins and disabling the perm for owners. And disabling it for owners preemptively locks the ability to change the group's perms. Locking the permission for owners will prevent this.

https://github.com/CivMC/NameLayer/pull/24

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
