### ISSUE TITLE
WorldUtils - Best Practices Switch Statements

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#15]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/WorldUtils.java#L33

* Issue:
Switch statements have no fall through prevention. This may lead to hard to debug bugs.

* Solution:
Add default case with throws.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
