### ISSUE TITLE
Should pearls also show where they were captured?

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#157]
Each pearl contains information about the circumstances of the pearling like who is pearled, when they were pearled, and who pearled them. It would be good, in my opinion, to also include where they were pearled. For clarity, I don't mean the current location of the pearl, but where the pearled-player died when they became pearled. This could add an interesting dynamic regarding jurisdiction and evidence, etc. Just an idea, it's not urgent or a demand.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
