### ISSUE TITLE
AbstractYLimitedArea - Caller Communication

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#17]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/model/AbstractYLimitedArea.java#L20

* Issue:
Method doesn't communicate dimension reduction for check.

* Solution:
Method should clearly communicate the dimension reduction that is checked by taking the exact Y value instead of the complete Location object.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
