### ISSUE TITLE
LocationTrackable - Abstract class offers no advantage

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#18]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/LocationTrackable.java#L7

* Issue:
Abstract class offers no real advantage over just copy pasting the few calls to the inheriting classes.

* Solution:
Eliminate class.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
