### ISSUE TITLE
Bans for multiaccounting ban all associated accounts

### ISSUE THREAD

**Issue by Inframission** [CivMC/Civ#184]
Players should be able to play up to the limit and only have extra accounts banned.

This probably happens because when a share ban is applied to an account, all associated accounts will get share banned on login.

 This is probably why `/forgive name shared` is also not pardoning accounts from future share bans unless all associated accounts are pardoned.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
