### ISSUE TITLE
 WorldIDManager.java - Failure of register

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#19]
* Code location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/WorldIDManager.java#L33

* Issue:
Setup of WorldIDManager may be incomplete without communicating the error state to the caller.

* Solution:
Setup should be done in the constructor with complete failure (throw Exception) on error to make sure that a half constructed object isn't used from the outside.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
