### ISSUE TITLE
Cactus growth stops randomly and restarts randomly

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#199]
Most commonly reported with Cactus, unsure if it is common to all vertical growers, or only cactus, or if this is an issue with all crops. Commonly reported after restart, cactus will stop growing when their timer is up and must be manually updated (by right clicking with a stick) for their growth to occur. However, sometimes they will get reset and all grow as they should be. This will affect entire farms, making entire farms stop growing until they get updated. Sometimes leaving and reloading the chunks update the crops, and reportedly sometimes it does not and only manually updating them works. 

This is tricky and hard to pinpoint, but it is an ongoing issue. Will update if I uncover more information.

**Comment by okx-code** [comment]
I don't think this is still an issue.
