### ISSUE TITLE
GlobalTrackableDAO - Advantages over interface?

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#21]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalTrackableDAO.java#L9

* Issue:
Class is abstract but may not offer anything that is worth inheriting instead of simply implementing.

* Solution:
Eliminate class.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
