### ISSUE TITLE
GlobalLocationTracker - Incoherent synchronization strategies

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#22]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L122
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L129

* Issue:
Synchronization strategies are wildly different across method calls. These methods lock `this`, while others use finegrained locking.

* Solution:
Unify synchronization by using concurrent structures.

* Related:
  - https://github.com/CivMC/Civ/issues/23

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
