### ISSUE TITLE
[Regression] Inconsistent message hover text

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/Civ#220]
The hover text on messages sent by the plugin is very inconsistent. Each message seems to do its own thing; some messages don't even provide any.

The expected behavior is that every message concerning a snitch should have a corresponding hover text with full info on the snitch.

For how it used to be done, see https://github.com/DevotedMC/JukeAlert/issues/24 and https://github.com/DevotedMC/JukeAlert/pull/36/.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
