### ISSUE TITLE
Indicate snitch aliveness upon destruction

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/Civ#221]
The message on snitch destruction should include whether the snitch is dormant or not.

This is in fact a regression created by the addition of snitch dormancy. Before, whether a destroyed snitch was alive or not was obvious, culled snitches didn't produce a message. Right now, dormant snitches [do show the message on destruction](https://github.com/CivMC/JukeAlert/blob/master/paper/src/main/java/com/untamedears/jukealert/model/appender/ShowOwnerOnDestroyAppender.java#L22) but there's no way to tell that the snitch is dormant. This introduces unnecessary ambiguity – knowing whether the owner of the snitch has spotted me destroying the snitch or not is vital information.

There are two options here:
 1. Simply do not show the message for dormant snitches. This is trivial to implement, just change [this boolean](https://github.com/CivMC/JukeAlert/blob/master/paper/src/main/java/com/untamedears/jukealert/model/appender/ShowOwnerOnDestroyAppender.java#L23), but probably incorrect. 
 2. Add the status of the snitch to the message, possibly as a hover event, though this information is vital so it should probably be included in the text. 

Current message:
 - Snitch was reinforced on *group* owned by *owner*

Proposed message: 
 - Alive Snitch was reinforced on *group* owned by *owner*
 - Dormant Snitch was reinforced on *group* owned by *owner*

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
