### ISSUE TITLE
Create small snitches

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#223]
This is possible with the addition of configurable snitch range for tall snitches. Just need to configure it for a small snitch too.

This was a player request, could use some discussion but they suggested it would be very useful for targeted tracking of a shop chest, so you don't get spam from the larger area around it.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
