### ISSUE TITLE
GlobalLocationTracker - Concurrent Code Enhancements

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#23]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L64
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L19
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L79

* Issue:
Locking maps and lists that could be a concurrent structure.

* Solution:
Use concurrent maps and lists instead of locking everything. This class could be fully synchronized atm and offers no real advantage for concurrent access.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
