### ISSUE TITLE
GlobalLocationTracker - Unsafe unload semantics

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#24]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L35
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/GlobalLocationTracker.java#L47

* Issue:
Unloading in a loop calling multiple "listeners" that may throw, but none of the exceptions are caught. This may lead to only half of all listeners being processed, none at all, and overall makes the unloading semantics of this method extremely complicated to grasp.

* Solution:
Enforce caller handling of errors, or enforce all processing with explicit error state communication between unload listeners.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
