### ISSUE TITLE
CMCWorldDAO - Dangerous connection management

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#25]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/CMCWorldDAO.java#L24
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/global/CMCWorldDAO.java#L56

* Issue:
Releasing and acquiring connections at multiple points while assuming a transaction that should envelope all statements is dangerous and may lead to deadlocks.

* Solution:
Refactor code to one shot transactional management and remove multiple instances where a connection is acquired.

* Related:
  - https://github.com/CivMC/Civ/issues/125

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
