### ISSUE TITLE
QTBoxImpl - Constructor doesn't communicate dimensional reduction

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#26]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/QTBoxImpl.java#L19

* Issue:
Constructor reduces the dimensionality of a location from 3 to 2. This should be explicitly comunicated.

* Solution:
Change signature of constructor to communicate the explicit projection or introduce a static constructor method.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
