### ISSUE TITLE
QTBoxImpl - Dangerous operations

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#27]
* Code Location:
https://github.com/CivMC/CivModCore/blob/00243ad09361361b46e808e3379eb739251a4365/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/QTBoxImpl.java#L12

* Issue:
Min and max values are never checked for validity, this may result in broken AABBs and may introduce bugs that are hard to track.

* Solution:
```java
	public QTBoxImpl(int lowerXBound, int upperXBound, int lowerZBound, int upperZBound) {
		this.lowerXBound = Math.min(lowerXBound, upperXBound);
		this.upperXBound = Math.max(lowerXBound, upperXBound);
		this.lowerZBound = Math.min(lowerZBound, upperZBound);
		this.upperZBound = Math.max(lowerZBound, upperZBound);
	}
```

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
