### ISSUE TITLE
SparseQuadTree - Typing issues

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#28]
* Code Location:
https://github.com/CivMC/CivModCore/blob/219fef98f8c9f8b3dfc45dea60e4ed50c2e7ec58/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java#L27
https://github.com/CivMC/CivModCore/blob/219fef98f8c9f8b3dfc45dea60e4ed50c2e7ec58/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java#L225

* Issue:
Fields and variables can be primitive types of type `int`.

* Solution:
Migrate type to int.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
