### ISSUE TITLE
SparseQuadTree - Quadrant storage in children

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#29]
* Code Location:
https://github.com/CivMC/CivModCore/blob/219fef98f8c9f8b3dfc45dea60e4ed50c2e7ec58/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java#L25

* Issue:
Children store their quadrant but not their parents, making bottom up traversal impossible without top down traversal first.

* Solution:
Store a reference to the parent node and query the parent node for the quadrant of the child, if necessary. But in generall Quadtree nodes do not need to know their own quadrants for spatial queries.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
