### ISSUE TITLE
SparseQuadTree - Incoherent Design

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#30]
* Code Location:
https://github.com/CivMC/CivModCore/blob/219fef98f8c9f8b3dfc45dea60e4ed50c2e7ec58/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java#L1

* Issue:
The node design for the SparseQuadTree is incoherent. There is an enum to signify quadrants (can be keys), but also the child nodes are split into their quadrants and occupy 4 fields.

* Solution:
Duplicate all quadrant structures to reflect the design choice, or have the child nodes in a map with quadrant as key.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
