### ISSUE TITLE
SparseQuadTree - Key Value Pairing

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#31]
* Code Location:
https://github.com/CivMC/CivModCore/blob/219fef98f8c9f8b3dfc45dea60e4ed50c2e7ec58/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java#L15

* Issue:
Trees and QuadTrees are generally key value pairings (just like maps).

* Solution:
Use <K, V> as the generic signature, where K is the key (bounding box), and V is the value.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
