### ISSUE TITLE
ChunkMeta Code Review - Method name is confusing.

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#33]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L95

* Issue:
`void deleteNonPersistentData();` may be a confusing name since the flag that is checked is named `if (!meta.loadAlways())` which is alwaysLoaded, not persistent.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
