### ISSUE TITLE
Baritone detection

### ISSUE THREAD

**Issue by okx-code** [CivMC/Civ#355]
Baritone is a commonly used, yet illegal, digbot, and shows distinctive patterns when being used. However, it does use some degree of randomisation to avoid detection by anti-cheats. We should add a way to alert admins when baritone is suspected to be used.

**Comment by MrJeremyFisher** [comment]
Does Vulcan not cover this?

**Comment by okx-code** [comment]
No, it's [explicitly a non-goal for Vulcan to detect automations](https://docs.google.com/document/u/1/d/e/2PACX-1vS0rprFtlkSQ8h1HtZcDhVW6JPllQb9T9j0OePmBzaMADGgD4J05335ULlyBCl84aePhP_W_r39vV0B/pub), because it is not really doing anything that you can't do in vanilla.

**Comment by MrJeremyFisher** [comment]
They [list it as a check on their spigot page](https://www.spigotmc.org/resources/vulcan-anti-cheat-advanced-cheat-detection-1-7-1-20-4.83626/#:~:text=W%2C%20X%2C%20Y-,-%20baritone%3A%20a%2C%20b,--%20Crash%3A%20A%2C%20B) though

**Comment by okx-code** [comment]
They do, we have it enabled, and it doesn't do anything.

**Comment by MrJeremyFisher** [comment]
It may be worth mentioning that to the people who develop it then. From what I've heard they're pretty responsive to reports of issues.

**Comment by okx-code** [comment]
I've already checked and found that policy. The Vulcan checks are probably only for really egregious baritne uses.

**Comment by AngrySoundTech** [comment]
Vulcan updates now detect better
