### ISSUE TITLE
Migrate CivDocker

### ISSUE THREAD

**Issue by Huskydog9988** [CivMC/Civ#359]
With the move to the mono repo, and #356, it seems like the logical next to move all of civ's codebase under one roof. On top of that, it would make releases significantly easier and simpler as plugins could be versioned under the civ version, instead of being independently versioned. (Tracking changes is a nightmare at present, at least for me.)

**Comment by RedDevel2** [comment]
We are doing this, just waiting until after the 1.26.4 patch.

**Comment by Huskydog9988** [comment]
Glad to hear it
