### ISSUE TITLE
ChunkMeta Code Review - Missing Default / Break

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#39]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L76

* Issue:
Swtich statement is missing a break & a default case.

* Solution:
```java
	private static void persistChunkMeta(ChunkMeta<?> chunkMeta) {
		switch (chunkMeta.getCacheState()) {
			case NORMAL:
				break;
			case MODIFIED:
				chunkMeta.update();
				break;
			case NEW:
				chunkMeta.insert();
				break;
			case DELETED:
				chunkMeta.delete();
				break;
			default:
				throw new UnsupportedOperationException("No branch for "+chunkMeta.getCacheState()+" state.");
		}
		chunkMeta.setCacheState(CacheState.NORMAL);
	}
```

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
