### ISSUE TITLE
ChunkMeta Code Review - World Object Reference Storage

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#40]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L32

* Issue:
Do not cache a reference to the world object, instead store the UUID and refetch the world object from the paper api on demand. There is no good reason as far as I know to keep the actual reference.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
