### ISSUE TITLE
ChunkMeta Code Review - World Object Reference Storage

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#41]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L37

* Issue:
This is a treemap, but a hashmap may be more efficient in the case of numeric keys.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
