### ISSUE TITLE
ChunkMeta Code Review - Persist & Persist All Semantics

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#42]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L59

* Issue:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L69
```java
	void persistPlugin(short id) {
		ChunkMeta<?> chunkMeta = chunkMetas.get(id);
		if (chunkMeta != null) {
			persistChunkMeta(chunkMeta);
		}
	}
```

This delegates exception handling and trouble shooting to the caller.

https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L59
```
	void fullyPersist() {
		for (ChunkMeta<?> chunkMeta : chunkMetas.values()) {
			persistChunkMeta(chunkMeta);
		}
	}
```

This delegates exception handling and trouble shooting to the caller, while being opaque about the actual safe-state of the chunkMeta values. 

* Solution(s):
Either have this method fully fail for all data on error, or provide a specific list of failed issues to the caller, or have a callback for each successful / unsuccessful persist. In all cases, storage should be clear to the caller requesting the storage what when and how many of the chunkMetas have been saved.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
