### ISSUE TITLE
ChunkMeta contains explicit thread parking

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#43]
* Code Location:
https://github.com/CivMC/CivModCore/blob/cab0ef422d9dffc081b271cc35b7a1b6f3dab68a/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java#L126

* Problem:
This code is synchronizing on the global "this" pointer, which may be stalling the main thread by requiring all other threads to stop on accessing any method on the object (synchronized calls only)

* Solution:

Migrate the isFullyLoaded to an atomic boolean, removed explicit thread parking.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
