### ISSUE TITLE
ManagedDatasource catches Throwable

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#44]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L355
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L414

* Problem:
Catches Throwable.

* Solution:
Narrow exception type to the appropriate level. Throwable includes a plethora of VM error states which shouldn't be catched but can be regarded as teminal operations for any VM. Error is a subtype, see https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
