### ISSUE TITLE
ManagedDatasource statement without effect

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#45]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L269

* Problem:
try {} has no effect if the exception thrown in checkWait() is a runtime exception.

* Solution:
Remove the try-block

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
