### ISSUE TITLE
Potential for re-enabling ice boating

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#451]
Ice boating, ie, using a boat on an ice-road, was disabled on Civclassics on 11th August 2020 ([SAH PR](https://github.com/CivClassic/SimpleAdminHacks/pull/30), [Ansible PR](https://github.com/CivClassic/AnsibleSetup/pull/83)), something which has been carried over to CivMC. I'd like to explore the idea of easing some of the restrictions on ice boating.

Referencing [this post](https://www.reddit.com/r/civclassics/comments/i7wkyp/should_ice_boats_be_disabled/g15co8z/), I submitted a new hack to SimpleAdminHacks that would eject players from boats travelling on particular blocks and likewise prevent boats from being placed on those blocks - after discovering that players could blue-ice boat at speeds of 75 blocks per second / 4,500 blocks per minute. It was thought to be too fast both because it upset the balance of long distance travel, particularly to/from/between vaults, but also because those speeds would horrendously lag the server by vitrue of all the chunks being loaded *and consequently their ChunkMeta data.* @Maxopoly tested out the older and slower forms of ice and believed them to be too fast too.

Should the admins be open to re-enabling ice boating, I feel the following should be investigated:

- Measuring the top speed of players scripting blue ice-road travel.
- Measuring the current strain of the server from players ice-roading about.
- Determining whether an individual player's tick-chunk load distance can be reduced.
- Determining whether a boat can be made to travel slower.

That first thing, the top speed of scripts, is perhaps the most important detail. I personally believe that ice blocks that boat at analogous speeds to those scripts should be allowed: I think players being able to use ice roads efficiently without using scripts is a good thing; it democratises travel.

**Comment by okx-code** [comment]
No potential sorry
