### ISSUE TITLE
ManagedDatasource registerMigration may swallow error states.

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#46]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L221
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L237

* Problem:
If a migration is already registered, the old one is dropped silently. This isn't optimal behaviour if not checked for identity of the migration object.

* Solution:
Throw an exception if a migration (by id) is already registered and let the caller explicitly know that a duplicate migration exists. Resolution can then be done by the caller.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
