### ISSUE TITLE
ManagedDatasource construction may fail silently

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#47]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ManagedDatasource.java#L187

* Problem:
The check fails silently if no returntype is checked by the caller. The proper behaviour should be a thrown nullpointerexception in this case.

* Solution:
Throw a nullpointerexception instead of silently warning to logs.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
