### ISSUE TITLE
ConnectionPool should specify transactional mode

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#48]
* Code Location:
https://github.com/CivMC/CivModCore/blob/master/paper/src/main/java/vg/civcraft/mc/civmodcore/dao/ConnectionPool.java

* Problem:
Intialization of the connection pool does not set any explicit transactional mode, and doesn't define a proper interface for callers to model transactions. This may be a source of dropped rows.

* Solution:
Set the transactional mode (auto commit or not.) in the connection pool for new connections and offer a transactional interface to callers.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
