### ISSUE TITLE
Implicit Transactions in AutoStorageEngine

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#49]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/auto/AutoStorageEngine.java#L35

* Problem:
Neither ManagedDataSource nor AutoStorageEngine open transactions nor do they commit implicit transactions. This may lead to dropped changes if the connection is not set to auto-commit on close. This may be a source of dropped rows that are never persisted in the database (if it's a transactional database).

* Solution:
Model transaction commit and handling explicit in either of those classes. ManagedDataSource can return a proxy connection object and commit on close, or handle rollbacks.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
