### ISSUE TITLE
BlockBasedChunkMeta wrong exception type

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#50]
* Code Location:
  https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L50
  https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L82
  https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L194
  https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L228

* Problem:
IllegalArgumentException is not the proper exception to throw on nullable references.

* Solution:
Use Objects.requireNonNull where appropriate.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
