### ISSUE TITLE
Beds not working intermittently after update to 1.20

### ISSUE THREAD

**Issue by AngrySoundTech** [CivMC/Civ#509]
Reported by a few separate players. 

- Beds may not work if they are against the wall.
- Beds may lose their spawn point occasionally?

Maybe something funky is going on. Look into it.

**Comment by RedDevel2** [comment]
It seems that the spawn of a player only resets when they logout without using /logout, this spawns a combat-logger. When this combat logger despawns after some time. And the player logs back in, their spawn is reset.

It is only after the combat logger despawns that the spawn is reset, if they login before it disappears they retain their set spawn at their bed. likewise with using /logout.

**Comment by RedDevel2** [comment]
Fixed with #535
