### ISSUE TITLE
BlockBasedChunkMeta extends java.util.Collection implicitly

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#51]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L24

* Problem:
The class seems to be implicitly implementing the collections interface while not maintaining the proper inheritance rules. This may be misleading for anyone interfacing with the class.

* Solution:
Add `extends Collection` and override the appropriate methods with the proper signatures.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
