### ISSUE TITLE
BlockBasedChunkMeta storage

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#52]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L35

* Problem:
There is no good justification for a generic array construction over using an ArrayList. Arrays have a static storage size, so the stored object here seems to already introduce another level of indirection, negating the O(1) access advantage of arrays.

* Solution:
Rewrite this with proper generic collections to make the code more clear.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
