### ISSUE TITLE
BlockBasedChunkMeta modulo operation

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#53]
* Code Location:
    https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L350

* Problem:
    Introducing an additional if leads to pipeline speculation and stalls in the worst case.

* Solution:
    The method here is equivalent to `((a % b) + b) % b` where `b = L4_Z_SECTION_LENGTH`. Maybe remove the method completely and inline the expression.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
