### ISSUE TITLE
BlockBasedChunkMeta Usage Requirements (Do not use unless chunk is loaded)

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#54]
* Code Location:
https://github.com/CivMC/CivModCore/blob/a71661ef833e938969c975c174e1bed4c28b00a5/paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/BlockBasedChunkMeta.java#L18

* Problem:
It's generally considered bad behaviour to have implicit, badly documented preconditions. BlockBasedChunkMeta seems to require a chunk to be loaded to be able to run.

* Solution:
Enforce chunk loaded state on construction and usage to ensure proper behaviour without requiring additional outside code to ensure preconditions for this class.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
