### ISSUE TITLE
Replacing disabling dolphingrace with listener for depth boots

### ISSUE THREAD

**Issue by Aiounnae** [CivMC/Civ#57]
Instead of completely disabling "DOLPHINS_GRACE"  in BuffSpanker, substitute it with a dedicated listener for enchantments on the player worn boots for any level (or just 2/3) of Depthstrider (the reason its disabled). 

Dolphin Grace without boots is slower than a horse and uses hunger, but is slightly faster than a boat that doesnt use hunger, ending up being balanced, while adding new ways of traversing water in an non op way (especially since food its harder to make than in vanilla, double price!).

((first issue submission ever))

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
