### ISSUE TITLE
Carpet/rail dupe prevention is redundant

### ISSUE THREAD

**Issue by NoOneTruePunk** [CivMC/Civ#61]
Rails and carpets are unpushable. If this is to prevent dupes it's redundant, as paper has since patched this after the simpleadminhacks fix was implemented.

allow-piston-duplication: false
https://github.com/CivMC/CivDocker/blob/master/paper/config/paper.yml#L99

This is the line that should handle it, which allows pushing without dupes.

https://github.com/CivMC/SimpleAdminHacks/blob/master/paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/GameFixesConfig.java#L51

This is the redundant line. If possible the redundant line should be set to false, dupe should be tested to confirm it's prevented by paper and functionality restored.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
