### ISSUE TITLE
Allow Vines to be harvested like Weeping Vines

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#62]
When harvesting Weeping Vines, you can break the top vine, you'll receive some or all of the connected vines. Currently, when harvesting Vines, you break the top vine and lose all connected vines, meaning you have to harvest vines one at a time, bottom to top, which is extremely awkward and unfun. As such, think Vines should be harvestable like Weeping Vines. You could then limit how far Vines will naturally grow, similarly to Weeping Vines.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
