### ISSUE TITLE
Potentially removing the bottle-cost for reclaiming XP?

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#63]
For those unaware, if you have levels and experience on your player, you can punch an [Enchanting Table](https://minecraft.fandom.com/wiki/Enchanting_Table) with [Glass Bottles](https://minecraft.fandom.com/wiki/Glass_Bottle) in hand and those bottles will be converted into [Bottle o' Enchanting](https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting). It's a nice QOL feature that, sadly, rarely gets used, and that's when players even know about it. I'd posit that this lack of use is mostly likely due to its costs.

For context, reclaiming experience has a 1:1 Glass Bottle to Bottle o' Enchanting cost ratio, on par with a Basic Cauldron, whereas an Advanced Cauldron has a 64:81 (or 0.79:1) ratio, which is a *massive* difference at scale... which is the point, yes, but the reclaim experience mechanic is a quality of life feature, not an economy of scale feature: XP markets wont collapse because of experience reclamation. People use, or would use it to reclaim leftover experience after enchanting, or to reclaim experience accidentally gained through accidental emerald levelling... we're talking about pittance xp here in the grand scheme, and yet there's a substantive costs to reclaiming it.

One cannot gain experience through any means except for the Cauldron factories, so an enormous amount of glass has already been spent to produce the experience. And one cannot reclaim the glass bottles from those Bottles o' Enchanting. For these reasons, I find the Glass Bottle cost to be cringe and yikes pilled and should be removed.

**Comment by Feathercrown** [comment]
If reclaiming gives you enough bottles to get up to the same amount of xp, you could theoretically transport an arbitrarily large amount of emeralds in your XP bar. That being said nobody would bother and the risk of dying with the levels balances it out.

**Comment by Protonull** [comment]
> you could theoretically transport an arbitrarily large amount of emeralds in your XP bar.

That's true, but at the point where XP is being transported, the bottles have already been spent in the making of the XP in the factories. Reclaiming the XP via an Enchanting Table just doubles the bottle cost... more than doubles.

**Comment by Solitaire7** [comment]
I would say instead of removing bottles from reclaiming entirely change it so that it only uses 1 bottle, so that when u reclaim holding a single bit it gets used up and gives you however many xp bottles are equivalent to your levels. You can't obtain glass bottles from bottles of xp so there's no risk of duping the glass bottles and it retains the symbolism of using a bottle to bottle your xp levels

**Comment by Protonull** [comment]
That seems fair, and means that players are unlikely to accidentally dump a whole bunch of XP bottles into their inventory because they punched an Enchanting Table.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
