### ISSUE TITLE
Prevent placing blocks on nether roof

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#64]
We utilize Paper's setting to give damage to kill a player if they are on the nether roof. But players still have time to place some blocks, or can use printer to place blocks above the nether roof. So we should disable block placement entirely.

**Comment by AngrySoundTech** [comment]
This PR needs to be moved to the monorepo

**Comment by Protonull** [comment]
> Should be implemented by a configurable per-dimension height limit

You could just piggyback off the Paper setting. It's a bit of a PITA to get to, but I was last able to access it with:
```java
((CraftWorld) world).getHandle().paperConfig.netherVoidTopDamageHeight
```

**Comment by drekamor** [comment]
Opened a PR https://github.com/CivMC/Civ/pull/634
