### ISSUE TITLE
Add an 'end-search' block to GoldBlockElevators

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#65]
Just an interesting feature request: I was wondering whether you'd consider adding a configurable kind of 'end-search' block to the GoldBlockElevators hack. Say there's a lodestone at y70 and a player crouches on it, if there's a 'end-search' block right underneath, then the search for a teleport destination fails immediately fails instead of searching for another 134 blocks. Likewise, if there's an 'end-search' block above the player when they jump, then the search similarly fails instead of searching for another 250 blocks.

**Comment by Feathercrown** [comment]
This would also allow you to protect elevators from unwated vertical entry, which is neat.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
