### ISSUE TITLE
Redesign elevator triggering

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/Civ#71]
Currently there are two ways to go up/down elevators that you can switch between via `/config`:
1. Jumping/Crouching
2. Right/Left clicking the elevator block

## 1. Jumping/Crouching

Pros:
 - Convenient, jumping and crouching intuitively maps to going up/down.
 - Works despite certain blocks on top of the lodestone, e.g. carpets, pressure plates.
 
Cons:
 - **Easy to trigger accidentally. This is especially relevant when it comes to traps, e.g. on iceroads.**

## 2. Right/Left clicking the elevator block

Pros
 - Hard to trigger accidentally, no real chance of inadvertedly triggering a trap.
 
Cons:
 - Right/Left clicking does not map to going up/down as intuitively as jumping/crouching.
 - Impossible to use on elevators that are covered by certain blocks like carpet. 
 - Right-clicking the elevator while having blocks selected will teleport the player, but also place a block on top of the elevator, blocking it.
 - Left-clicking the elevator with a pickaxe runs the risk of breaking it.

## Summary

The default setting `1.` is unusable due to the danger of traps, but setting `2.` is inconvenient and doesn't work in a lot of scenarios.

## Solutions

1. Ideally the two approaches would be unified into one. 
2. Fix the setting `2.` to work the same as `1.`:
  - Perhaps allow right-clicking a block above the elevator to teleport, to enable using elevators covered with e.g. carpets.
  - Perhaps cancel block break/placement events when on top of an elevator.
3. Maybe have a new way of triggering the elevator, one that doesn't have side-effects.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
