### ISSUE TITLE
Improve bound armor by allowing other wearers with nerfs?

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#73]
On Civrealms you could still wear armor that had been bound to another player, but the armor was nerfed heavily. This allowed it to still be used to some degree, such as for vanity or junk prot.

Is this something CivMC wants to do? I imagine it would require tie-ins with Finale in order to modify the armor stats.

**Comment by okx-code** [comment]
This issue is not something that can be implementated by anyone, and needs to be better scoped. I'm closing this as won't fix.
