### ISSUE TITLE
HackManager is very complicated for the purpose it serves

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#79]
* Code Location:
https://github.com/CivMC/SimpleAdminHacks/blob/master/paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/framework/HackManager.java

* Issue:
The class seems to be loading plugins by doing class discovery, via methods that aren't guaranteed to be always working. This seems to serve the purpose to replace a simple list or map of objects with "new" constructors on hacks/plugins, and uses reflection for methods that could be demanded from implementing the interfaces for those hacks in the first place.

* Solution:
This is a bit over the top for what it does and could be simplified by reordering the loading of hacks. Use a simple list of newly constructed objects to implement the same functionality with more clarity.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
