### ISSUE TITLE
Nonsensical Method

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#80]
* Code Location:
https://github.com/CivMC/SimpleAdminHacks/blob/927ba898f2bf8cf65edb2550b946a8375b0f2293/paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/SimpleAdminHacks.java#L68

* Issue:
getClassLoader is guaranteed by the java standard to exist on class objects. [See here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getClassLoader()), the only case where this is null is the bootstrap classloader, which can't be accessed by userspace code easily anyways. This method does nothing but hide the well known access location of getClassLoader.

* Solution:
Remove this method.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
