### ISSUE TITLE
Minecarts & Pistons need management

### ISSUE THREAD

**Issue by psygate** [CivMC/Civ#82]
SimpleAdminHacks needs limits for minecarts & pistons. See [Thread](https://discord.com/channels/912074050086502470/919348449407815680/989921554106298429)

Related / Same? https://github.com/CivMC/Civ/issues/89

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
