### ISSUE TITLE
Remove the "Broadcast your kills" setting

### ISSUE THREAD

**Issue by Protonull** [CivMC/Civ#91]
# I'M NOT SAYING THAT KILLS SHOULDN'T BE BROADCAST!

When Maxopoly [added kill broadcasts](https://github.com/CivMC/CivChat2/commit/2e95170e909f8bc5a1b9f94224776d1a1ad9a690), he also added a setting allowing you to disable broadcasts your kills. When I asked him about this he [said](https://discord.com/channels/493148446610423828/612456224960806941/774719147581374495) that the feature was "very intentional" to allow for assassinations. I think players should be able to disable receiving kill notifications if they aren't bothered about that kind of information, but I do think, as I did then, that allowing people to disable their own kill broadcasts gives a massive advantage not only to assassins, but to client mods like interpol (or other pvp mods) which would effectively reimplement kill broadcasts. I just think kill broadcasts should be enabled for everyone.

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
